apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: dev-svcs
spec:
  serviceName: postgres-service
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        app: main
      serviceAccountName: wema-dev-sa
      tolerations:
        - key: "services"
          operator: "Equal"
          value: "postgres"
          effect: "NoSchedule"
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "wema"
            - name: POSTGRES_USER
              value: "wema_core"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: db-init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-init-scripts
          configMap:
            name: postgres-init-scripts
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: postgres-storage-class
        resources:
          requests:
            storage: 5Gi
