apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: dev-svcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        app: dev
      tolerations:
        - key: "services"
          operator: "Equal"
          value: "main"
          effect: "NoSchedule"
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "wema"
            - name: POSTGRES_USER
              value: "wema_core"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: db-init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: db-init-scripts
          configMap:
            name: postgres-init-scripts
