# Alternative PV configuration for EKS using EBS CSI driver
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-eks
  namespace: dev-svcs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-xxxxxxxxx  # Replace with your actual EBS volume ID
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.ebs.csi.aws.com/zone
          operator: In
          values:
          - us-west-2a  # Replace with your actual AZ
