apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-postgres-1
  namespace: dev-svcs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-gp3