apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-postgres-0
  namespace: dev-svcs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
  volumeName: postgres-pv
