apiVersion: v1
kind: Service
metadata:
  name: dev-postgres-service
  namespace: dev-svcs
spec:
  clusterIP: None
  ports:
    - port: 6444
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
