apiVersion: v1
kind: Service
metadata:
  labels:
    app: gatway
  name: gatway-service
  namespace: dev-svcs
spec:
  ports:
    - name: app-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: gatway