apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.8.2
    helm.sh/chart: argo-cd-5.43.8
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: "false"
  server.rbac.log.enforce.enable: "false"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
  url: https://localhost:8080
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: Ov23liV1ywxVsIpvqoGW
        clientSecret: 03466320c88f364f15f14ed72bab3aabd1b79580
        redirectURI: https://localhost:8080/auth/callback

