apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
  namespace: dev-svcs  
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        app: dev 
      tolerations:
        - key: "services"
          operator: "Equal"
          value: "main"
          effect: "NoSchedule"
      containers:
        - name: master
          image: redis
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /redis-master-data
            - name: redis-conf
              mountPath: /redis-master
      volumes:
        - name: redis-data
          emptyDir: { }
        - name: redis-conf
          configMap:
            name: redis-conf-config-map
            items:
              - key: redis-config
                path: redis.conf

