apiVersion: v1
kind: Service
metadata:
  labels:
    app: appointment
  name: appointment-service
  namespace: dev-svcs
spec:
  ports:
    - name: app-port
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: appointment
