apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification
  name: notification-service
  namespace: dev-svcs
spec:
  ports:
    - name: app-port
      port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    app: notification