apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment
  name: payment-service
  namespace: dev-svcs
spec:
  ports:
    - name: app-port
      port: 9002
      protocol: TCP
      targetPort: 9002
  selector:
    app: payment